version: '2.2'

services:

  common-service:
    image: ${SERVICE_IMAGE}
    build: ./src
    restart: on-failure
    env_file:
      - config/rutorrent/app.env
    logging:
      driver: "json-file"
      options:
        max-file: '2'
        max-size: 10m
 