version: '2.2'

services:

  build-base:
    image: "${SERVICE_IMAGE}_base"
    build:
      target: osbuild
      context: ./src/build
    command: php -v

  rutorrent-build:
    image: "${RUTORRENT_IMAGE}:${RUTORRENT_VER}"
    build:
      target: rutorrent_src
      args:
        RUTORRENT_VER: ${RUTORRENT_VER}
      context: ./src/build
    depends_on:
      build-base:
        condition: service_completed_successfully

  common-service:
    image: ${SERVICE_IMAGE}
    build:
      target: appbuild
      args:
        FILEMANAGER_VER: ${FILEMANAGER_VER}
        FILEMANAGER_SHARE_VER: ${FILEMANAGER_SHARE_VER}
        FILEMANAGER_MEDIA_VER: ${FILEMANAGER_MEDIA_VER}
      context: ./src/build
    depends_on:
      rutorrent-build:
        condition: service_completed_successfully
    restart: on-failure
    env_file:
      - config/app.env
    logging:
      driver: "json-file"
      options:
        max-file: '2'
        max-size: 10m
