version: '2.2'

services:

  common-service:
    image: ${SERVICE_IMAGE}
    build:
      #target: appbuild
      args:
        FILEMANAGER_VER: master
        RUTORRENT_VER: master
        FILEMANAGER_SHARE_VER: master
        FILEMANAGER_MEDIA_VER: master
      context: ./src/build
    restart: on-failure
    env_file:
      - config/rutorrent/app.env
    logging:
      driver: "json-file"
      options:
        max-file: '2'
        max-size: 10m
