version: '2.2'

services:

  common-service:
    image: ${SERVICE_IMAGE}
    restart: on-failure
    env_file:
      - config/rutorrent/app.env
    logging:
      driver: "json-file"
      options:
        max-file: '2'
        max-size: 10m

  service_x64:
    image: ${SERVICE_IMAGE}
    build:
      target: appbuild
      args:
        FILEMANAGER_VER: master
        BUILDPLATFORM: linux/amd64
      context: ./src/build

  service_x86:
    image: ${SERVICE_IMAGE}
    build:
      target: appbuild
      args:
        BUILDPLATFORM: linux/386
      context: ./src/build

  service_arm64:
    image: ${SERVICE_IMAGE}
    build:
      target: appbuild
      args:
        BUILDPLATFORM: linux/arm64
      context: ./src/build

  service_arm32:
    image: ${SERVICE_IMAGE}
    build:
      target: appbuild
      args:
        BUILDPLATFORM: linux/arm/v7
      context: ./src/build