services:

  build-base:
    image: "${RUTORRENT_IMAGE}:base"
    build:
      target: osbuild
      args:
        RUTORRENT_VER: ${RUTORRENT_VER}
      context: ./src/build
    command: php -v

  rutorrent-build:
    image: "${RUTORRENT_IMAGE}:${RUTORRENT_VER}"
    extends:
      service: build-base
    build:
      target: rutorrent_src
      args:
        RUTORRENT_VER: ${RUTORRENT_VER}

  common-service:
    image: ${SERVICE_IMAGE}
    build:
      target: appbuild
      args:
        RUTORRENT_IMG_SRC: "${RUTORRENT_IMAGE}:${RUTORRENT_VER}"
        RUTORRENT_VER: ${RUTORRENT_VER}
        FILEMANAGER_VER: ${FILEMANAGER_VER}
        FILEMANAGER_SHARE_VER: ${FILEMANAGER_SHARE_VER}
        FILEMANAGER_MEDIA_VER: ${FILEMANAGER_MEDIA_VER}
      context: ./src/build
    restart: on-failure
    env_file:
      - config/app.env
    logging:
      driver: "json-file"
      options:
        max-file: '2'
        max-size: 10m
