version: '2.2'

services:

  # apache front
  web:
    extends:
      service: common-service
      file: common.yml
    restart: always
    volumes:
      - ./src/rutorrent:/usr/src/app
      - ./config/rutorrent/media.php:/usr/src/app/plugins/filemanager-media/conf.php:ro
      - ./config/rutorrent/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ${LOGS_DIR}:/var/log/rutorrent:rw
      - ${RUTORRENT_TEMP_DIR}:/tmp:rw
      - ${RUTORRENT_DATA_DIR}/downloads:/data/downloads:rw
      - /mnt/store:/data/archive:rw
      - ${RUTORRENT_DATA_DIR}/.session:/data/.session:rw
      - ${RUTORRENT_SHARE_DIR}:/usr/src/app/share:rw

    expose:
      - 80
    networks:
      - default
      - webgateway  
    labels:
       - "traefik.enable=true"
       - "traefik.docker.network=webrouter_gateway"
       - "traefik.http.routers.rutorrent.rule=PathPrefix(`/rt/`)"
       - "traefik.http.routers.rutorrent.entrypoints=web,websecure"
       - "traefik.http.middlewares.strip-rutorrent-prefix.stripprefix.prefixes=/rt/"
       - "traefik.http.middlewares.rutorrentAuth.basicauth.users=admin:$$apr1$$tVlulz88$$ppMBNuyJMWvpcFDZRPuAv1"
       - "traefik.http.middlewares.rutorrentAuth.basicauth.removeheader=true"
       - "traefik.http.routers.rutorrent.middlewares=strip-rutorrent-prefix@docker,rutorrentAuth@docker"

  # php wamp server
  rtorrent:
    extends:
      service: common-service
      file: common.yml
    command: gosu runuser sh -c '/bin/rm -rf /data/.session/rtorrent.lock && rtorrent || rtorrent'
    restart: always
    stdin_open: true
    tty: true
    networks:
      default:
        ipv4_address: 172.200.23.3
    volumes_from:
      - web:rw
    volumes:
#      - ./config/rtorrent.conf:/var/www/.rtorrent.rc:rw
      - ./config/rtorrent.conf:/home/runuser/.rtorrent.rc:rw
      - ${LOGS_DIR}:/var/log/rutorrent:rw
      - ${RUTORRENT_TEMP_DIR}:/tmp:rw
      - ${RUTORRENT_DATA_DIR}/downloads:/data/downloads:rw
      - /mnt/store:/data/archive:rw
      - ${RUTORRENT_DATA_DIR}/.session:/data/.session:rw
    expose:
      - "5000"
    ports:
      - "55950-56000:55950-56000/tcp"
      - "55950-56000:55950-56000/udp"


networks:
  webgateway:
    external:
      name: webrouter_gateway
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.200.23.0/24
        