# with traefik support on /rt/ endpoint

services:

  # apache front
  web:
    extends:
      service: common-service
      file: common.yml
    restart: always
    volumes:
      - tempdir:/tmp:rw
      - persistent_data:/data:rw
# override image configurations
#      - ./config/rutorrent/config.php:/usr/src/app/conf/config.php:ro
    # uncomment if traefik is not used
    ports:
      - "80:80/tcp"
    expose:
      - 80
    networks:
      - default
#      - webgateway  #traefik network
    labels:
       - "traefik.enable=true"
       - "traefik.docker.network=webrouter_gateway"
       - "traefik.http.routers.rutorrent.rule=PathPrefix(`/rt/`)"
       - "traefik.http.routers.rutorrent.entrypoints=web,websecure"
       - "traefik.http.middlewares.strip-rutorrent-prefix.stripprefix.prefixes=/rt/"
       - "traefik.http.middlewares.rutorrentAuth.basicauth.users=admin:$$apr1$$tVlulz88$$ppMBNuyJMWvpcFDZRPuAv1"
       - "traefik.http.middlewares.rutorrentAuth.basicauth.removeheader=true"
       - "traefik.http.routers.rutorrent.middlewares=strip-rutorrent-prefix@docker,rutorrentAuth@docker"

  # jailed rtorrent xml-rpc server
  rtorrent:
    extends:
      service: common-service
      file: common.yml
    command: su -P -l -c sh -c '/bin/rm -rf /data/.session/rtorrent.lock ; exec rtorrent' - runuser
    restart: always
    stdin_open: true
    tty: true
    volumes_from:
      - web:rw
    expose:
      - "5000"
    ports:
      - "55950-55999:55950-55999/tcp"
      - "55950-55999:55950-55999/udp"
    labels:
      - "traefik.enable=false"

volumes:
  tempdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PERSISTENT_DATA_DIR}/tmp
  persistent_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PERSISTENT_DATA_DIR}/data

networks:
  default:
#  webgateway:
#    external: true
#    name: webrouter_gateway

        