name: Multiarch Docker Image Build

on:
  release:
    types: [published]
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/build/**'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - './.env'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # setup Docker buildx action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Setup buildx
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx create --name builder --driver docker-container --use && docker buildx inspect --bootstrap
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: export $(grep -v '^#' .env | xargs) && docker buildx bake -f common.yml --set *.platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7 --set *.tags=unzel/rutorrent-filemanager:latest --set *.tags=unzel/rutorrent-filemanager:${GITHUB_REF} --push
