name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/build/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/build/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # setup Docker buildx action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: export $(grep -v '^#' .env | xargs) && docker build ./src/build/ --file ./src/build/Dockerfile --tag unzel/rutorrent-filemanager:latest --tag ${SERVICE_IMAGE}
    - name: Docker Push
      run: docker push unzel/rutorrent-filemanager
