name: Multiarch Build

on:
  release:
    types: [published]
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/build/**'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - './.env'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # setup Docker buildx action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Setup buildx
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx create --name builder --driver docker-container --use && docker buildx inspect --bootstrap
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push base image if needed
      run: |
        export $(grep -v '^#' stable.env | xargs) 
        if docker pull "$SERVICE_IMAGE_base" > /dev/null 2>&1; then
          echo "Base image found, using cache."
          echo "build_base=false" >> "$GITHUB_ENV"
        else
          echo "Base image not found, will build it."
          echo "build_base=true" >> "$GITHUB_ENV"
          docker buildx bake -f common.yml --set *.platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7 --push build-base 
        fi

    - name: Build the Docker images
      run: |
        export $(grep -v '^#' stable.env | xargs) 
        docker buildx bake -f common.yml --set *.platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7 --push rutorrent-build \
        && docker buildx bake -f common.yml --set *.platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7 --push common-service
