name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/build/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/build/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # setup Docker buildx action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: export $(grep -v '^#' .env | xargs) && docker buildx bake -f common.yml --set *.platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7 --set *.tags=unzel/rutorrent-filemanager:latest --set *.tags=${SERVICE_IMAGE} --push
